Emulator_one:
  platformName: Android
  automationName: UiAutomator2
  platformVersion: "13.0"
  language: en
  locale: US
  deviceName: emulator-5554
  appActivity: com.android.calculator2.Calculator
  appPackage: com.google.android.calculator
  noReset: false
  udid: emulator-5554

Pixel6:
  platformName: Android
  automationName: UiAutomator2
  platformVersion: "13.0"
  language: en
  locale: US
  deviceName: 1A061FDF600EYC
  appActivity: com.android.calculator2.Calculator
  appPackage: com.google.android.calculator # adb shell pm list packages
  noReset: false
  udid: 1A061FDF600EYC
