name: Appium CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        api-level: [25] #Google api level for example [25,23,28]
        target: [default]
    steps:
      - uses: actions/checkout@v2 #checkout the code
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: |
          npm install -g appium@v1.20.2
          appium -v
          appium &>/dev/null &
      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
        with:
          api-level: 33
          target: 13
          arch: x86_64
          profile: Pixel 6
          script: ./python run_case.py # running our test with info to check the results

