name: Appium CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        api-level: [33]
        target: [google_apis]
    steps:
      - uses: actions/checkout@v2 #checkout the code
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          npm install -g appium@v1.22.3
          appium -v
          appium &>/dev/null &
      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2.26.0 # install and create the Emulator
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Pixel 6
          script: ./python run_case.py # running our test with info to check the results

